import { AgeGroupMeta, DailyPlan } from './types';

export const AGE_GROUPS: AgeGroupMeta[] = [
  {
    id: '0-3',
    name: '0-3 Ay',
    rangeText: 'Yeni Doğan & İlk Bakış',
    badgeText: '0-3 AY',
    colorTheme: {
      bg: 'bg-rose-50/70',
      text: 'text-rose-900',
      border: 'border-rose-200',
      gradient: 'from-rose-400 to-pink-500',
      badgeBg: 'bg-rose-100 text-rose-700',
      activeTab: 'bg-rose-500 text-white shadow-rose-200',
    },
    iconName: 'Baby',
    description: 'Yüksek kontrastlı şekiller, emzirme & pijama giyme rutini, sevgi dolu anne-bebek seslenişleri.',
  },
  {
    id: '3-6',
    name: '3-6 Ay',
    rangeText: 'Gülümseme & Sesleri Tanıma',
    badgeText: '3-6 AY',
    colorTheme: {
      bg: 'bg-amber-50/70',
      text: 'text-amber-900',
      border: 'border-amber-200',
      gradient: 'from-amber-400 to-orange-500',
      badgeBg: 'bg-amber-100 text-amber-800',
      activeTab: 'bg-amber-500 text-white shadow-amber-200',
    },
    iconName: 'Smile',
    description: 'Su, süt gibi ilk kelimeler, 4 zaman çekimli fiiller ve duygu dolu diyaloglar.',
  },
  {
    id: '6-12',
    name: '6-12 Ay',
    rangeText: 'Keşif & İlk İşaretler (Baby Signs)',
    badgeText: '6-12 AY',
    colorTheme: {
      bg: 'bg-sky-50/70',
      text: 'text-sky-900',
      border: 'border-sky-200',
      gradient: 'from-sky-400 to-indigo-500',
      badgeBg: 'bg-sky-100 text-sky-800',
      activeTab: 'bg-sky-500 text-white shadow-sky-200',
    },
    iconName: 'Compass',
    description: 'Burun, beşik, süt ve günlük kurallar. İşaret dili (Baby Sign) ve göster-tekrarla modeli.',
  },
  {
    id: '12-24',
    name: '12-24 Ay',
    rangeText: 'İlk Kelimeler & Çevre Etkileşimi',
    badgeText: '12+ AY',
    colorTheme: {
      bg: 'bg-emerald-50/70',
      text: 'text-emerald-900',
      border: 'border-emerald-200',
      gradient: 'from-emerald-400 to-teal-500',
      badgeBg: 'bg-emerald-100 text-emerald-800',
      activeTab: 'bg-emerald-500 text-white shadow-emerald-200',
    },
    iconName: 'Sparkles',
    description: 'Uğur böcekleri, mandal, renkler ve nesnelerle günlük aktivitelerde konuşma.',
  },
];

export const INITIAL_PLANS: DailyPlan[] = [
  // ================= 0-3 AY - GÜN 1 =================
  {
    id: '0-3-day-1',
    ageGroupId: '0-3',
    dayNumber: 1,
    title: '1. Gün: Miniğim Kitabı, Arı & Sevgi Dolu Emzirme',
    subtitle: '0-3 Aylık Bebeğimin İlk İngilizce Kelimeleri ve Rutinleri',
    focus: 'Miniğim Kitabı: Bee 🐝 & Breastfeeding Rutini',
    principle: 'Sakin ve yumuşak bir ses tonuyla bebeğinizle göz teması kurun.',
    affirmation: {
      english: 'You are deeply loved, my sweet baby.',
      turkish: 'Sen derinden seviliyorsun, tatlı bebeğim.',
      phonetic: 'Yu ar dipli lavd, may sviit beybi.',
    },
    sections: [
      {
        id: 'sec-bee-dialogue',
        type: 'dialogue',
        title: 'Miniğim Kitabı: Bee 🐝 (Arı)',
        subtitle: 'Bebeğimle arı hakkında İngilizce neler konuşabilirim?',
        badge: 'Karşılıklı Diyalog',
        icon: 'BookOpen',
        howToApplyList: [
          'Bebeğinize arı görselini veya oyuncağını gösterin.',
          'Arı sesini taklit ederek ("Bzzz!") konuşmayı eğlenceli hale getirin.',
          'Gözlerinin içine bakarak sevgiyle gülümseyin.',
        ],
        items: [
          {
            id: 'bee-1',
            dialogueSpeaker: 'Anne / Baba',
            english: 'Buzzing bee! Buzzing bee!',
            turkish: 'Vızvız arı! Vızvız arı!',
            phonetic: 'Baz-ing bii! Baz-ing bii!',
            icon: '🐝',
          },
          {
            id: 'bee-2',
            dialogueSpeaker: 'Bebek Adına',
            english: 'Hi buzzing bee!',
            turkish: 'Merhaba vızvız arı!',
            phonetic: 'Hay baz-ing bii!',
            icon: '👋',
          },
          {
            id: 'bee-3',
            dialogueSpeaker: 'Anne / Baba',
            english: 'Do you make honey?',
            turkish: 'Bal yapar mısın?',
            phonetic: 'Du yu meyk hani?',
            icon: '🍯',
          },
          {
            id: 'bee-4',
            dialogueSpeaker: 'Bebek Adına',
            english: 'Yes, I do.',
            turkish: 'Evet yaparım.',
            phonetic: 'Yes, ay du.',
            icon: '✨',
          },
          {
            id: 'bee-5',
            dialogueSpeaker: 'Anne / Baba',
            english: 'Do you have wings?',
            turkish: 'Kanatların var mı?',
            phonetic: 'Du yu hev vingz?',
            icon: '🪽',
          },
          {
            id: 'bee-6',
            dialogueSpeaker: 'Bebek Adına',
            english: 'Yes, I have.',
            turkish: 'Evet var.',
            phonetic: 'Yes, ay hev.',
            icon: '💛',
          },
          {
            id: 'bee-7',
            dialogueSpeaker: 'Anne / Baba',
            english: 'Can you fly?',
            turkish: 'Uçabilir misin?',
            phonetic: 'Ken yu flay?',
            icon: '🌸',
          },
          {
            id: 'bee-8',
            dialogueSpeaker: 'Bebek Adına',
            english: 'Yes I can.',
            turkish: 'Evet uçabilirim.',
            phonetic: 'Yes ay ken.',
            icon: '🎉',
          },
        ],
      },
      {
        id: 'sec-breastfeeding',
        type: 'routine',
        title: 'Breastfeeding a Baby (Bebeği Emzirme & Besleme)',
        subtitle: 'Emzirirken veya biberon verirken bebeğinizle kuracağınız bağ',
        badge: 'Günlük Rutin',
        icon: 'Heart',
        howToApplyList: [
          'Bebeğinizi ten tene yakın tutun.',
          'Cümleleri fısıldar gibi sakin ve melodik bir ritimle söyleyin.',
          'Beslenme bittiğinde sırtını sıvazlarken teşekkür edin.',
        ],
        items: [
          {
            id: 'bf-1',
            english: "It's time for milk, my little one.",
            turkish: 'Süt zamanı, küçüğüm.',
            phonetic: 'İts taym for miılk, may litıl van.',
            icon: '🍼',
          },
          {
            id: 'bf-2',
            english: "Come, let's have some milk together.",
            turkish: 'Gel, birlikte biraz süt içelim.',
            phonetic: 'Kam, lets hev sam miılk tıgedır.',
            icon: '🥛',
          },
          {
            id: 'bf-3',
            english: 'Drink slowly, my love, and enjoy your milk.',
            turkish: 'Yavaşça iç, aşkım, sütünün tadını çıkar.',
            phonetic: 'Drink slovli, may lav, end incoy yor miılk.',
            icon: '❤️',
          },
          {
            id: 'bf-4',
            english: "You're doing great, sweetheart.",
            turkish: 'Harika yapıyorsun, canım.',
            phonetic: 'Yur duing greyt, sviithart.',
            icon: '⭐',
          },
          {
            id: 'bf-5',
            english: 'Close your eyes and relax while you nurse.',
            turkish: 'Gözlerini kapat ve emerken rahatla.',
            phonetic: 'Kloz yor ayz end rileks vayl yu nörs.',
            icon: '🌙',
          },
        ],
      },
      {
        id: 'sec-baby-care',
        type: 'routine',
        title: 'Bebek Bakımı: Giydirme & Uyku Öncesi',
        subtitle: 'Zıbın ve pijama giydirirken maruz bırakma cümleleri',
        badge: 'Öz Bakım',
        icon: 'Sparkles',
        howToApplyList: [
          'Kıyafetleri giydirirken kollarını ve bacaklarını nazikçe tutun.',
          'Göz teması kurarak tebessüm edin.',
        ],
        items: [
          {
            id: 'care-1',
            english: "Let's put on your soft pajamas, my little angel.",
            turkish: 'Haydi, yumuşak pijamalarını giyelim, küçük meleğim.',
            phonetic: 'Lets put on yor soft picamaz, may litıl eyincıl.',
            icon: '🧸',
          },
          {
            id: 'care-2',
            english: 'Time to slip your tiny arms into this cute onesie.',
            turkish: 'Minik kollarını bu tatlı zıbına sokma zamanı.',
            phonetic: 'Taym tu slip yor tayni armz intu dis kyuut vanzi.',
            icon: '👕',
          },
          {
            id: 'care-3',
            english: 'Lift your legs gently, sweetheart, so we can put on your cozy socks.',
            turkish: 'Bacaklarını nazikçe kaldır canım, böylece sıcak çoraplarını giyebiliriz.',
            phonetic: 'Lift yor legz centli, sviithart, so vi ken put on yor kozi saks.',
            icon: '🧦',
          },
          {
            id: 'care-4',
            english: 'Look how adorable you are in your little outfit!',
            turkish: 'Küçük kıyafetinde ne kadar sevimlisin!',
            phonetic: 'Luk hav edorıbıl yu ar in yor litıl avtfit!',
            icon: '🥰',
          },
        ],
      },
    ],
    flashcards: [
      {
        id: 'fc-contrast-happy',
        title: 'Happy Face',
        turkishTitle: 'Mutlu Yüz (Göz Gelişimi)',
        emoji: '🙂',
        contrastType: 'high-contrast',
        description: '0-3 ay bebeklerin odaklanması için siyah-beyaz yüksek kontrast gülen yüz.',
        audioPrompt: 'Look at the smiling baby! Happy face!',
      },
      {
        id: 'fc-contrast-sheep',
        title: 'Little Sheep',
        turkishTitle: 'Küçük Kuzu / Koyun',
        emoji: '🐑',
        contrastType: 'high-contrast',
        description: 'Siyah-beyaz siluet koyun kartı, görsel takip yeteneğini güçlendirir.',
        audioPrompt: 'A cute little sheep. Baa baa!',
      },
      {
        id: 'fc-bee',
        title: 'Buzzing Bee',
        turkishTitle: 'Vızvız Arı',
        emoji: '🐝',
        contrastType: 'colorful',
        description: 'Sarı-siyah renkli dost arı.',
        audioPrompt: 'Buzzing bee! Can you fly?',
      },
      {
        id: 'fc-nursing',
        title: 'Sweet Milk',
        turkishTitle: 'Anne Sütü & Sevgi',
        emoji: '🍼',
        contrastType: 'colorful',
        description: 'Derinden seviliyorsun, tatlı bebeğim.',
        audioPrompt: 'It is time for milk, my little one.',
      },
    ],
  },

  // ================= 3-6 AY - GÜN 3 =================
  {
    id: '3-6-day-3',
    ageGroupId: '3-6',
    dayNumber: 3,
    title: '3. Gün Ödevimiz: Su, 4 Zaman Çekimli Fiiller ve Duygular',
    subtitle: '3-6 Aylık Bebeğimin İngilizce Kelimeleri',
    focus: 'Water (Su), Drink (4 Zaman), Emotions (Duygular)',
    principle: 'Mimikler, suyun serinliği ve sevgi dolu ses tonuyla öğrenmeyi pekiştirin.',
    affirmation: {
      english: 'Mommy loves you very much! Daddy is here to give you hugs and kisses!',
      turkish: 'Anneciğin seni çok seviyor! Babacığın seni kucaklamak ve öpmek için burada!',
      phonetic: 'Mami lavs yu veri maç! Dedi iz hir tu giv yu hags end kisiz!',
    },
    sections: [
      {
        id: 'sec-water-words',
        type: 'vocabulary',
        title: '3-6 Aylık Bebeğimin İngilizce Kelimeleri: Water (Su)',
        subtitle: 'Su ile ilgili günlük konuşmalar [Okunuşu: Votır]',
        badge: 'Kelime & Cümle',
        icon: 'Droplets',
        howToApplyList: [
          'Elini yıkarken veya banyo yaptırırken suyu hissettirin.',
          'Bardağa su dökerken "Let\'s pour the water" deyin.',
        ],
        items: [
          {
            id: 'water-1',
            english: 'The water is flowing from the tap.',
            turkish: 'Musluktan su akıyor.',
            phonetic: 'Dı votır iz floving from dı tep.',
            icon: '🚰',
          },
          {
            id: 'water-2',
            english: 'The water is nice and cool.',
            turkish: 'Su güzel ve serin.',
            phonetic: 'Dı votır iz nais end kuul.',
            icon: '💧',
          },
          {
            id: 'water-3',
            english: "Let's pour the water into the glass.",
            turkish: 'Haydi suyu bardağa dökelim.',
            phonetic: 'Lets por dı votır intu dı glas.',
            icon: '🥛',
          },
          {
            id: 'water-4',
            english: 'Water is good for us.',
            turkish: 'Su bizim için iyidir.',
            phonetic: 'Votır iz gud for as.',
            icon: '💖',
          },
          {
            id: 'water-5',
            english: 'I am splashing the water.',
            turkish: 'Suyu sıçratıyorum.',
            phonetic: 'Ay em splaşing dı votır.',
            icon: '💦',
          },
        ],
      },
      {
        id: 'sec-drink-grammar',
        type: 'grammar_tenses',
        title: '3-6 Aylık Bebekler İçin 4 Zaman Çekimli Fiiller: Drink (İçmek)',
        subtitle: 'Bebekler aynı fiili farklı zamanlarda duyarak gramer yapısını doğal edinirler [Okunuşu: Drink]',
        badge: '4 Zaman Çekimi',
        icon: 'Clock',
        howToApplyList: [
          'Süt içerken şimdiki zamanı, bittikten sonra geçmiş zamanı, hazırlarken gelecek zamanı kullanın.',
        ],
        items: [
          {
            id: 'drink-cont',
            tenseTag: 'Şimdiki Zaman (Present Continuous)',
            english: 'You are drinking milk.',
            turkish: 'Süt içiyorsun!',
            phonetic: 'Yu ar drinking miılk.',
            icon: '🍼',
          },
          {
            id: 'drink-past',
            tenseTag: 'Geçmiş Zaman (Simple Past)',
            english: 'Yesterday, you drank a lot of milk.',
            turkish: 'Dün çok süt içtin!',
            phonetic: 'Yestırdey, yu drenk a lat of miılk.',
            icon: '🗓️',
          },
          {
            id: 'drink-future',
            tenseTag: 'Gelecek Zaman (Future Tense)',
            english: 'In the morning, you will drink more milk.',
            turkish: 'Sabahleyin daha çok süt içeceksin!',
            phonetic: 'İn dı morning, yu vil drink mor miılk.',
            icon: '☀️',
          },
          {
            id: 'drink-simple',
            tenseTag: 'Geniş Zaman (Simple Present)',
            english: 'You always drink milk with a happy face!',
            turkish: 'Her zaman mutlu bir yüzle süt içersin!',
            phonetic: 'Yu olveys drink miılk vit e hepi feys!',
            icon: '😊',
          },
        ],
      },
      {
        id: 'sec-emotions',
        type: 'emotions',
        title: 'Emotions: Duygular & Sevgi Bağı',
        subtitle: 'Miniğimizle duygularımız ile ilgili tatlı tatlı konuşabiliriz',
        badge: 'Duygusal Gelişim',
        icon: 'Smile',
        howToApplyList: [
          'Güldüğünde ve ağladığında bu cümlelerle duygusuna ayna olun.',
          'Göz göze gelin, sıcacık sarılın.',
        ],
        items: [
          {
            id: 'emo-1',
            english: 'Mommy loves you very much!',
            turkish: 'Anneciğin seni çok seviyor!',
            phonetic: 'Mami lavs yu veri maç!',
            icon: '👩‍🍼',
          },
          {
            id: 'emo-2',
            english: "Daddy's here to give you hugs and kisses!",
            turkish: 'Babacığın seni kucaklamak ve öpmek için burada!',
            phonetic: 'Dediz hir tu giv yu hags end kisiz!',
            icon: '👨‍🍼',
          },
          {
            id: 'emo-3',
            english: 'You make me smile every day!',
            turkish: 'Her gün beni güldürüyorsun!',
            phonetic: 'Yu meyk mi smayl evri dey!',
            icon: '🌟',
          },
          {
            id: 'emo-4',
            english: 'When you laugh, it fills my heart with joy!',
            turkish: 'Güldüğünde, kalbim sevinçle doluyor.',
            phonetic: 'Ven yu laf, it filz may hart vit coy!',
            icon: '🥰',
          },
          {
            id: 'emo-5',
            english: "Even when you cry, I'll always be here to comfort you.",
            turkish: 'Ağladığında bile, seni rahatlatmak için buradayım.',
            phonetic: 'İvın ven yu kray, ayl olveys bi hir tu kamfırt yu.',
            icon: '🤗',
          },
        ],
      },
    ],
    flashcards: [
      {
        id: 'fc-water',
        title: 'Water',
        turkishTitle: 'Su (Votır)',
        emoji: '💧',
        contrastType: 'colorful',
        description: 'Temiz, serin ve ferahlatıcı su.',
        audioPrompt: 'The water is flowing from the tap. Nice and cool water!',
      },
      {
        id: 'fc-bottle',
        title: 'Drink Milk',
        turkishTitle: 'Süt İçmek (Drink)',
        emoji: '🍼',
        contrastType: 'colorful',
        description: 'Mutlu yüzle içilen lezzetli süt.',
        audioPrompt: 'You are drinking milk with a happy face!',
      },
      {
        id: 'fc-smile',
        title: 'Happy Smile',
        turkishTitle: 'Mutlu Tebessüm',
        emoji: '👶',
        contrastType: 'colorful',
        description: 'Her gün kalbimizi neşeyle dolduran gülüş.',
        audioPrompt: 'You make me smile every day!',
      },
    ],
  },

  // ================= 6-12 AY - GÜN 1 =================
  {
    id: '6-12-day-1',
    ageGroupId: '6-12',
    dayNumber: 1,
    title: '1 Günlük İngilizce Plan: Burun, Beşik, Süt ve Rutinler',
    subtitle: 'Bugün yapılacak tüm görevler! Her aktivite 5-10 dakika konuş, göster, tekrarla ve eğlen!',
    focus: 'Nose (Burun), Crib (Beşik), Milk (Süt), Must (Zorunluluk)',
    principle: 'TEKRAR - SABIR - SEVGİ = ÖĞRENME. Her gün aynı uygulama.',
    affirmation: {
      english: 'Good job! You did it! You are learning and growing with love.',
      turkish: 'Aferin! Başardın! Sevgiyle öğreniyor ve büyüyorsun.',
      phonetic: 'Gud cab! Yu did it! Yu ar lörning end growing vit lav.',
    },
    sections: [
      {
        id: 'sec-nose',
        type: 'action_guide',
        title: 'NOSE (BURUN) - Konuş, Göster, Tekrarla',
        subtitle: 'Vücut organlarını tanıma ve dokunarak öğrenme',
        badge: 'Organlar & Beden',
        icon: 'Smile',
        howToApplyList: [
          'Kendi burnuna ve bebeğin burnuna nazikçe dokun.',
          'Cümleleri neşeyle ve melodik sesle tekrarla.',
          'Gülümse ve göz teması kur!',
        ],
        items: [
          {
            id: 'nose-1',
            english: 'Touch your nose.',
            turkish: 'Burnuna dokun.',
            phonetic: 'Taç yor noz.',
            icon: '👃',
          },
          {
            id: 'nose-2',
            english: 'Where is your nose?',
            turkish: 'Burnun nerede?',
            phonetic: 'Ver iz yor noz?',
            icon: '❓',
          },
          {
            id: 'nose-3',
            english: 'Mommy has a nose too.',
            turkish: 'Annenin de burnu var.',
            phonetic: 'Mami hez e noz tu.',
            icon: '👩‍🦰',
          },
          {
            id: 'nose-4',
            english: 'Can you wiggle your nose?',
            turkish: 'Burnunu oynatabilir misin?',
            phonetic: 'Ken yu vigıl yor noz?',
            icon: '🐰',
          },
          {
            id: 'nose-5',
            english: 'Your nose is very cute!',
            turkish: 'Burnun çok tatlı!',
            phonetic: 'Yor noz iz veri kyuut!',
            icon: '✨',
          },
        ],
      },
      {
        id: 'sec-crib',
        type: 'action_guide',
        title: 'CRIB (BEŞİK) - Uyku Rutini & Güven',
        subtitle: 'Beşiği göster, sallarken konuş ve güven ver',
        badge: 'Uyku Zamanı',
        icon: 'Moon',
        howToApplyList: [
          'Beşiği göster ve bebeğini yatırırken/sallarken konuş.',
          'Sevgi dolu, sakinleştirici bir ses tonu kullan.',
          'Rutinleri tekrarla, güven hissini artır!',
        ],
        items: [
          {
            id: 'crib-1',
            english: 'Babies sleep in the crib.',
            turkish: 'Bebekler beşikte uyur.',
            phonetic: 'Beybiz sliip in dı krib.',
            icon: '🛏️',
          },
          {
            id: 'crib-2',
            english: 'You also have a crib.',
            turkish: 'Senin de bir beşiğin var.',
            phonetic: 'Yu olso hev e krib.',
            icon: '⭐',
          },
          {
            id: 'crib-3',
            english: "I'm rocking you now.",
            turkish: 'Seni sallıyorum şimdi.',
            phonetic: 'Aym raking yu nav.',
            icon: '🎶',
          },
          {
            id: 'crib-4',
            english: 'Babies love sleeping in the crib, dear.',
            turkish: 'Bebekler beşikte uyumayı sever, canım.',
            phonetic: 'Beybiz lav sliiping in dı krib, diır.',
            icon: '💤',
          },
          {
            id: 'crib-5',
            english: 'Shall I put you in your crib?',
            turkish: 'Seni beşiğine koyayım mı?',
            phonetic: 'Şel ay put yu in yor krib?',
            icon: '👶',
          },
        ],
      },
      {
        id: 'sec-milk-sign',
        type: 'action_guide',
        title: 'MILK (SÜT) - Bebek İşaret Dili (Baby Sign)',
        subtitle: 'Süt şişesini göster, işaretini yap: İşaret + Kelime = Anlama',
        badge: 'İşaret Dili (Sign)',
        icon: 'Droplet',
        howToApplyList: [
          'Elini sık ve yumruğunu açıp kapat (bebek süt işareti).',
          'Bebeğin işareti görsün ve taklit etsin.',
          'Süt zamanını keyifli hale getir!',
        ],
        items: [
          {
            id: 'milk-1',
            english: 'Do you want some milk? Here is your milk!',
            turkish: 'Süt ister misin? İşte sütün!',
            phonetic: 'Du yu vant sam miılk? Hir iz yor miılk!',
            icon: '🍼',
          },
          {
            id: 'milk-2',
            english: 'You can ask for milk like this.',
            turkish: 'Sütü böyle isteyebilirsin.',
            phonetic: 'Yu ken esk for miılk layk dis.',
            icon: '✊✋',
          },
          {
            id: 'milk-3',
            english: 'Milk! Milk! Milk!',
            turkish: 'Süt! Süt! Süt! (işaretini yaparak)',
            phonetic: 'Miılk! Miılk! Miılk!',
            icon: '✨',
          },
          {
            id: 'milk-4',
            english: 'I love milk!',
            turkish: 'Sütü seviyorum!',
            phonetic: 'Ay lav miılk!',
            icon: '🥛',
          },
        ],
      },
      {
        id: 'sec-must-routine',
        type: 'action_guide',
        title: 'MUST (ZORUNLULUK / KURAL) - Rutinleri Pekiştirme',
        subtitle: 'Rutin zamanı kullan, pekiştir: Rutin + Tekrar = Öğrenme',
        badge: 'Günlük Rutinler',
        icon: 'CheckCircle',
        howToApplyList: [
          'Rutin zamanlarda kullan (süt, uyku, yemek).',
          'Nazik ama net bir tonla söyle.',
          'Olumlu pekiştir!',
        ],
        items: [
          {
            id: 'must-1',
            english: 'You must drink your milk now.',
            turkish: 'Şimdi sütünü içmelisin.',
            phonetic: 'Yu mast drink yor miılk nav.',
            icon: '⏰',
          },
          {
            id: 'must-2',
            english: 'We must eat healthy food.',
            turkish: 'Sağlıklı yiyecekler yemeliyiz.',
            phonetic: 'Vi mast iit helt-i fuud.',
            icon: '🥣',
          },
          {
            id: 'must-3',
            english: 'You must sleep in your crib.',
            turkish: 'Beşiğinde uyumalısın.',
            phonetic: 'Yu mast sliip in yor krib.',
            icon: '🌙',
          },
          {
            id: 'must-4',
            english: 'Good job! You did it!',
            turkish: 'Aferin! Başardın!',
            phonetic: 'Gud cab! Yu did it!',
            icon: '🎉',
          },
        ],
      },
    ],
    flashcards: [
      {
        id: 'fc-nose',
        title: 'Nose',
        turkishTitle: 'Burun (Noz)',
        emoji: '👃',
        contrastType: 'colorful',
        description: 'Touch your nose! Can you wiggle your nose?',
        audioPrompt: 'Touch your nose! Where is your nose?',
      },
      {
        id: 'fc-crib',
        title: 'Crib',
        turkishTitle: 'Beşik (Krib)',
        emoji: '🛏️',
        contrastType: 'colorful',
        description: 'Babies sleep in the crib. Cozy and safe.',
        audioPrompt: 'Babies sleep in the crib. I am rocking you now.',
      },
      {
        id: 'fc-milk',
        title: 'Milk',
        turkishTitle: 'Süt (Miılk)',
        emoji: '🍼',
        contrastType: 'colorful',
        description: 'Yumruğunu aç-kapa süt işareti!',
        audioPrompt: 'Here is your milk! Milk, milk, milk!',
      },
    ],
  },

  // ================= 12-24 AY - GÜN 1 =================
  {
    id: '12-24-day-1',
    ageGroupId: '12-24',
    dayNumber: 1,
    title: 'Day 1: Ladybugs & Clothespin (Uğur Böcekleri ve Mandal)',
    subtitle: 'Gözlem, Renkler ve Günlük Nesnelerle İngilizce Konuşma',
    focus: 'Ladybugs (Uğur Böcekleri) & Clothespin (Mandal)',
    principle: 'Birlikte nesnelere dokunarak ve göstererek öğrenin.',
    affirmation: {
      english: 'You are loved. Yes, you are loved! Great job! You did great today!',
      turkish: 'Seviliyorsun. Evet, sen seviliyorsun! Harika iş çıkardın!',
      phonetic: 'Yu ar lavd. Yes, yu ar lavd! Greyt cab! Yu did greyt tudey!',
    },
    sections: [
      {
        id: 'sec-ladybugs',
        type: 'vocabulary',
        title: 'LADYBUGS (Uğur Böcekleri)',
        subtitle: 'Renkler, sayılar ve doğa gözlemi',
        badge: 'Doğa & Renkler',
        icon: 'Sparkles',
        howToApplyList: [
          'Görseldeki uğur böceklerini tek tek parmağınızla sayın.',
          'Renkleri vurgulayarak söyleyin (red and black / pink with yellow spots).',
        ],
        items: [
          {
            id: 'lady-1',
            english: 'There are two ladybugs.',
            turkish: 'İki uğur böceği var.',
            phonetic: 'Der ar tu leydibagz.',
            icon: '🐞🐞',
          },
          {
            id: 'lady-2',
            english: 'One of them is red and black.',
            turkish: 'Biri kırmızı ve siyah.',
            phonetic: 'Van of dem iz red end blek.',
            icon: '🐞',
          },
          {
            id: 'lady-3',
            english: 'Look, this one is red and black.',
            turkish: 'Bak, bu kırmızı ve siyah.',
            phonetic: 'Luk, dis van iz red end blek.',
            icon: '👀',
          },
          {
            id: 'lady-4',
            english: 'The other one is pink with yellow spots on it.',
            turkish: 'Diğeri pembe renkte ve üzerinde sarı noktalar var.',
            phonetic: 'Di adır van iz pink vit yelou spots on it.',
            icon: '🌸',
          },
          {
            id: 'lady-5',
            english: "Ladybugs feed on insects' eggs.",
            turkish: 'Uğur böcekleri böcek yumurtaları ile beslenirler.',
            phonetic: 'Leydibagz fiid on inseks egz.',
            icon: '🍃',
          },
        ],
      },
      {
        id: 'sec-clothespin',
        type: 'vocabulary',
        title: 'CLOTHESPIN (Mandal)',
        subtitle: 'Evdeki nesnelerle motor beceri ve dil gelişimi',
        badge: 'Günlük Nesneler',
        icon: 'Tag',
        howToApplyList: [
          'Çamaşır asarken kırmızı mandalı eline verip tutmasını sağlayın.',
          'Parmaklarını sıkıştırmaması için rehberlik edin.',
        ],
        items: [
          {
            id: 'pin-1',
            english: "Let's put the clothespin on the clothes.",
            turkish: 'Hadi mandalı kıyafetlere takalım.',
            phonetic: 'Lets put dı klots-pin on dı klots.',
            icon: '🧺',
          },
          {
            id: 'pin-2',
            english: 'Can you hold the clothespin?',
            turkish: 'Mandalı tutabilir misin?',
            phonetic: 'Ken yu hold dı klots-pin?',
            icon: '🤲',
          },
          {
            id: 'pin-3',
            english: 'The clothespin is red.',
            turkish: 'Mandal kırmızı.',
            phonetic: 'Dı klots-pin iz red.',
            icon: '🔴',
          },
          {
            id: 'pin-4',
            english: 'We use a clothespin to hang clothes.',
            turkish: 'Kıyafet asmak için mandal kullanıyoruz.',
            phonetic: 'Vi yuuz e klots-pin tu heng klots.',
            icon: '👕',
          },
          {
            id: 'pin-5',
            english: 'Be careful not to pinch your fingers with the clothespin.',
            turkish: 'Parmaklarını mandalla sıkıştırmamaya dikkat et!',
            phonetic: 'Bi kerful nat tu pinç yor fingırz vit dı klots-pin.',
            icon: '⚠️',
          },
        ],
      },
      {
        id: 'sec-review',
        type: 'review',
        title: "LET'S REVIEW! (Tekrar Edelim)",
        subtitle: 'Bugün neler öğrendik? Kısa bir pekiştirme yapalım!',
        badge: 'Günün Özeti',
        icon: 'CheckCircle',
        howToApplyList: [
          'Kırmızı rengi gösterip "It is red" deyin.',
          'Birlikte kıyafete mandal takın ve alkışlayın!',
        ],
        items: [
          {
            id: 'rev-1',
            english: 'It is red.',
            turkish: 'Kırmızı.',
            phonetic: 'It iz red.',
            icon: '🔴',
          },
          {
            id: 'rev-2',
            english: 'There are two ladybugs.',
            turkish: 'İki uğur böceği var.',
            phonetic: 'Der ar tu leydibagz.',
            icon: '🐞',
          },
          {
            id: 'rev-3',
            english: 'We use a clothespin to hang clothes.',
            turkish: 'Kıyafet asmak için mandal kullanırız.',
            phonetic: 'Vi yuuz e klots-pin tu heng klots.',
            icon: '👕',
          },
        ],
      },
    ],
    flashcards: [
      {
        id: 'fc-ladybugs',
        title: 'Two Ladybugs',
        turkishTitle: 'İki Uğur Böceği',
        emoji: '🐞',
        contrastType: 'colorful',
        description: 'Biri kırmızı-siyah, diğeri pembe sarı noktalı.',
        audioPrompt: 'There are two ladybugs! One is red and black.',
      },
      {
        id: 'fc-clothespin',
        title: 'Red Clothespin',
        turkishTitle: 'Kırmızı Mandal',
        emoji: '🧷',
        contrastType: 'colorful',
        description: 'Çamaşır asmak için kullanılan mandal.',
        audioPrompt: 'Can you hold the red clothespin?',
      },
      {
        id: 'fc-loved',
        title: 'You Are Loved',
        turkishTitle: 'Çok Seviliyorsun',
        emoji: '🌈',
        contrastType: 'colorful',
        description: 'Gökkuşağı ve kalplerle dolu sevgi mesajı.',
        audioPrompt: 'You are loved. Yes, you are deeply loved!',
      },
    ],
  },
];
